### ISSUE TITLE
Python 2.6 compatibility

### ISSUE THREAD

**Issue by gsong** [55minutes/python-epo-ops-client#17]
Tests are failing for Python 2.6 on Travis. Drop support or figure out what's wrong.

**Comment by hugovk** [comment]
Drop support.

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by gsong** [comment]
@hugovk Agreed. Dropping.
