### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by daniel-vcodex** [55minutes/python-epo-ops-client#21]
Hi,

Since last night, I'm having problems sending requests to EPO OPS.

For example, with python-epo-ops-client v2.3.0:
```python
import epo_ops
import epo_ops.models
client = epo_ops.Client(key='X', secret='X')
inp = epo_ops.models.Epodoc('CA826085')
client.published_data(reference_type='publication', input=inp, endpoint='biblio')
```

And I receive a 500 error with the body:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <fault xmlns="http://ops.epo.org">
    <code>SERVER.NotSupported</code>
    <message>An unknown error occurred. Please contact Open Patent Services Team (http://forums.epo.org/open-patent-services-and-publication-server-web-service)</message>
   </fault>
```

It seems that yesterday a patch was released for OPS:  https://forums.epo.org/maintenance-release-of-open-patent-services-ops-v-3-2-expected-soon-7224 

I've noticed that this works fine:
```
curl -X POST --header "Authorization: Bearer XXX" --header "Content-Type: text/plain" -d "(CA826085)" "http://ops.epo.org/3.2/rest-services/published-data/publication/epodoc/biblio"
```

But it generates a 500 error if the Content-Type header is missing:
```
curl -X POST --header "Authorization: Bearer XXX" -d "(CA826085)" "http://ops.epo.org/3.2/rest-services/published-data/publication/epodoc/biblio"
```

In epo_ops/api.py:64 _post method, a default 'Content-type' headers needs to be provided:
```python
    def _post(self, url, data, extra_headers=None, params=None):
        headers = {
            'Accept': self.accept_type,
            'Content-Type': 'text/plain'
        }
        headers.update(extra_headers or {})
        return self.request.post(
            url, data=data, headers=headers, params=params
        )
```

**Comment by perolovjonsson** [comment]
Hello, I started to use this library today and have similar problems. Apparently it is due to a new version upgrade that does not support earlier style POSTs. This is what someone wrote in the Forum for OPS

We have analysed the problem and found that there was a change in the OPS 3.2 service so that for POST requests no other "Content-Type" header is anymore supported as the "Content-Type: text/plain". All the years before we used in our application for the Content-Type header the string "application/x-www-form-urlencoded" which still works in the OPS 3.1 service.

Grateful if this could be fixed. PS Newbie on Python AND OPS so bear with me if this is all known to U.

**Comment by perolovjonsson** [comment]
Here are some links that I think are related to the problem

https://forums.epo.org/400-bad-request-http-error-code-using-post-7285

https://forums.epo.org/open-patent-services-ops-and-raw-data-subscription-products-35/?sid=e4a05d91df37d479971e48cc23d3b2ff

https://forums.epo.org/maintenance-release-of-open-patent-services-ops-v-3-2-expected-soon-7224?sid=e4a05d91df37d479971e48cc23d3b2ff

https://forums.epo.org/internal-server-error-7282
